import Link from 'next/link';
import Image from 'next/image';
import { ArrowLink, BookCta, Eyebrow } from '../../components/SiteShell';
import { BreadcrumbJsonLd, pageMetadata } from '../../lib/seo';

export const metadata = pageMetadata({ title: 'Aisha’s ADAPTOR example', description: 'See how Aisha, an illustrative executive assistant, moves from Work Profile and personal SWOT to a goal, actions and review.', path: '/examples/aisha/', image: { url: '/personas/aisha.jpg', alt: 'Illustration of Aisha', width: 1254, height: 1254 } });

export default function AishaPage() {
  return <main>
    <BreadcrumbJsonLd items={[{ name: 'Home', path: '/' }, { name: 'People and examples', path: '/examples/' }, { name: 'Aisha', path: '/examples/aisha/' }]} />
    <section className="article-hero"><div className="container persona-hero"><div><Eyebrow>Illustrative example · Executive assistant</Eyebrow><h1>Aisha: making hidden judgement visible.</h1><p className="lede">Aisha supports two directors in a professional services firm. As they begin using AI for drafts, summaries and document searches, she considers what they still rely on her to notice and handle.</p><p>Her response grows from the work those directors still depend on her to do.</p></div><Image className="persona-portrait persona-portrait-feature" src="/personas/aisha.jpg" width={1254} height={1254} alt="Illustration of Aisha" /></div></section>
    <section className="section"><div className="container split"><div><Eyebrow>01 · Profile</Eyebrow><h2>Where her work sits.</h2><p>Her main contribution is keeping schedules, information and follow-up dependable. She also handles sensitive relationships and coordinates between teams.</p></div><div className="workbook-panel"><p><strong>Primary:</strong> Administrative Operator</p><p><strong>Secondary:</strong> none at the same level</p><p><strong>Supporting:</strong> Team Coordinator and Relationship Worker</p><p><strong>Desired:</strong> Team Coordinator</p><p>That desired direction grows from coordination work she already does.</p></div></div></section>
    <section className="section section-tight blue-band"><div className="container"><Eyebrow>02 · Personal AI-Era SWOT</Eyebrow><h2>Four findings that shape her response.</h2><p className="section-intro">Aisha chooses the signals she can see in her own working week.</p><div className="swot-grid"><article className="swot-card"><h3>Strength</h3><p>She spots the sensitive exception behind an apparently routine meeting or request and knows when to warn, pause or escalate.</p></article><article className="swot-card"><h3>Weakness</h3><p>Much of her visible output is routine scheduling, notes and follow-up; the judgement that prevents problems can be hard for others to see.</p></article><article className="swot-card"><h3>Opportunity</h3><p>AI drafts could give her more time to check meaning, coordinate follow-up and show where human review adds value.</p></article><article className="swot-card"><h3>Threat</h3><p>If directors self-serve routine work, leaders may see less need for assistants while overlooking context, timing and discretion.</p></article></div></div></section>
    <section className="section"><div className="container split"><div><Eyebrow>03 · Goal</Eyebrow><h2>A three-month outcome.</h2></div><div className="prose"><p><strong>Aisha wants the directors to recognise her judgement around meeting exceptions, timing and sensitive follow-up.</strong> This goal responds to the self-service threat by using a strength she already demonstrates.</p><p>The directors will see the contribution she wants to grow, alongside the meeting pack they receive.</p></div></div></section>
    <section className="section section-tight blue-band"><div className="container"><Eyebrow>04 · Action and review</Eyebrow><h2>Put the judgement next to the output.</h2><div className="example-chain"><article><h3>First actions</h3><ul><li>Add a short judgement note to weekly executive meeting packs.</li><li>Flag sensitive follow-up with the context needed to act well.</li><li>Ask a director which part of that judgement helped.</li></ul></article><article><h3>What the review revealed</h3><p>After several packs, one director began asking what needed attention before the pack was final. Aisha also found that sensitive judgement needed careful wording. She kept the note and refined how she expressed it.</p></article></div><p className="example-caveat">The director’s response gives Aisha something concrete to build on while the firm decides how its administrative roles will change.</p></div></section>
    <section className="section"><div className="container split"><div><Eyebrow>What this illustrates</Eyebrow><h2>Show the judgement behind the task.</h2></div><div className="prose"><p>Aisha’s Profile points to administrative work. Her SWOT brings a sharper concern into view: will leaders notice the judgement around that work as routine outputs become easier to produce?</p><p>For a broader view of this kind of work, see <Link className="inline-link" href="/profiles/administrative-operators/">Administrative Operators</Link>. Your own Profile and SWOT will depend on the responsibilities and changes you can see in your work.</p><ArrowLink href="/examples/">Meet the five people</ArrowLink></div></div></section>
    <section className="section"><div className="container"><BookCta /></div></section>
  </main>;
}
