import Link from 'next/link';
import Image from 'next/image';
import { ArrowLink, BookCta, Eyebrow } from '../components/SiteShell';
import { BreadcrumbJsonLd } from '../lib/seo';

export default function AnalystWalkthrough() {
  return <main>
    <BreadcrumbJsonLd items={[{ name: 'Home', path: '/' }, { name: 'Work Profiles', path: '/profiles/' }, { name: 'Analysts', path: '/profiles/analysts/' }]} />
    <section className="article-hero"><div className="container work-profile-hero"><div><Eyebrow>Work Profile · Generic illustration</Eyebrow><h1><span className="profile-inline-letter" aria-hidden="true">A</span> Analysts</h1><p className="lede">Analysts research, compare, interpret and explain information so others can make decisions. AI can make the first pass faster. The value of the role may depend increasingly on framing the question, checking the evidence and explaining what the findings mean in context.</p></div><Image className="work-profile-hero-image" src="/work-profiles/analysts.jpg" width={1254} height={1254} alt="Analysis reports and charts with a magnifying glass checking a trend" /></div></section>
    <section className="section"><div className="container split"><div><Eyebrow>01 · Profile</Eyebrow><h2>What the work contributes.</h2><p>Analyst work appears in research, reporting, operations, finance, product and many other roles. A typical analyst gathers sources, compares options, tests explanations and makes a finding useful to someone deciding what to do.</p><p>It often combines with another Work Profile. A person who mainly advises clients might be a Professional Advisor with Analyst work in support; a technical builder who diagnoses system problems might show the reverse mix.</p></div><div className="workbook-panel"><Eyebrow>How AI may change the work</Eyebrow><h3>Faster output changes expectations.</h3><p>AI can summarise sources, produce charts and draft plausible recommendations. That may reduce time spent on routine reporting and allow decision makers to self-serve a first answer.</p><p>It can also raise the volume of material that needs checking. A polished report is useful only when its sources, assumptions and interpretation withstand scrutiny.</p></div></div></section>
    <section className="section section-tight blue-band"><div className="container"><Eyebrow>02 · A typical AI-Era SWOT</Eyebrow><h2>Signals an analyst might test against their own work.</h2><p className="section-intro">These are illustrative possibilities. They need evidence from a particular role before they become a personal SWOT.</p><div className="swot-grid"><article className="swot-card"><h3>Strength</h3><p>Can spot when a decision rests on a weak question, a missing source or an assumption that the data does not support.</p></article><article className="swot-card"><h3>Weakness</h3><p>Much of the visible contribution is recurring report production, while the judgement behind source selection and interpretation remains unseen.</p></article><article className="swot-card"><h3>Opportunity</h3><p>Use AI to compare more explanations, then become more valuable by validating evidence and presenting the real choices for a decision.</p></article><article className="swot-card"><h3>Threat</h3><p>Leaders may rely on self-service summaries or expect more reports in less time, without allowing enough scrutiny of how the conclusions were reached.</p></article></div></div></section>
    <section className="section"><div className="container split"><div><Eyebrow>03 · An illustrative goal</Eyebrow><h2>Move closer to the decision.</h2></div><div className="prose"><p>Suppose a team analyst’s monthly performance report is increasingly drafted with AI. A useful <strong>medium-term goal</strong> could be: over the next six months, become the person decision makers consult to test the evidence and options behind one recurring operational decision.</p><p>The goal responds to self-service reporting and uses the analyst’s strength in evidence quality. Better decision support will show whether the shift is working.</p></div></div></section>
    <section className="section section-tight blue-band"><div className="container"><Eyebrow>04 · Possible actions and review</Eyebrow><h2>Make the reasoning useful to someone else.</h2><div className="example-chain"><article><h3>First moves</h3><ul><li>Choose one recurring decision that uses the report.</li><li>For the next report, add a short note on the key assumption, an alternative explanation and the decision each would support.</li><li>Ask the decision owner which part helped and what was missing.</li></ul></article><article><h3>What to review</h3><p>After two reporting cycles, check whether the note changed the discussion, uncovered a weak assumption or simply added reading. Keep, shorten or change the approach based on that feedback.</p></article></div><p className="example-caveat">The right next move for another analyst will depend on their career stage, organisation and evidence.</p></div></section>
    <section className="section"><div className="container split"><div><Eyebrow>Apply the lens carefully</Eyebrow><h2>One Work Profile is rarely the whole role.</h2></div><div className="prose"><p>Compare Analyst work with any other <Link className="inline-link" href="/profiles/">Work Profiles</Link> in your role. A useful SWOT will draw on your own decisions, results and responsibilities.</p><ArrowLink href="/examples/">See five individual examples</ArrowLink></div></div></section>
    <section className="section"><div className="container"><BookCta /></div></section>
  </main>;
}
